name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup submodules
        run: git submodule update --init

      - name: Setup chksum64 and bass
        run: |
          mkdir -p tmp
          cd tmp
          wget https://raw.githubusercontent.com/DragonMinded/libdragon/trunk/tools/chksum64.c
          gcc chksum64.c -o chksum64
          sudo mv chksum64 /bin/
          git clone https://github.com/ARM9/bass.git
          cd bass/bass
          git checkout v14
          make
          sudo mv bass /bin/

      - name: Build Tests
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
          cd src
          zip dillon-n64-tests.zip *.z64

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest Development Version"
          files: |
            build/src/*.z64
            build/src/dillon-n64-tests.zip